WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/SupplierElement.xaml, WPFTesting/WPFTesting/SupplierElement.xaml.cs
Added event to modify line positions when an endpoint is produced.
=> Lines for endpoints update now.

WPFTesting/SpecFlowSupplyChain.MainWindow/Features/CheapestPath.feature.cs, WPFTesting/SpecFlowSupplyChain.MainWindow/Features/MainWindow.feature.cs, WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/ComponentToProductTransformer.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/IVendor.cs, WPFTesting/WPFTesting/Models/Supplier.cs
Tests written for:
- Process
- Receive
- ShipOrder
Bugs fixed for:
- Process
- Receive
Other stories completed:
- Window starts in full screen
- EndpointNode displays profit
=> EndpointNode tests & bugfixing

WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/ShippingLineElement.xaml, WPFTesting/WPFTesting/ShippingLineElement.xaml.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
Added Details Sidebar element to MainWindow.XAML Added event to highlight EndpointElement with a border Added precursor to auto-bound data binding.
Added event to highlight EndpointElement with a border
Added precursor to auto-bound data binding.
=> Endpoint details sidebar in progress.

WPFTesting/WPFTesting/Components/INodeElement.cs, WPFTesting/WPFTesting/Data/GenneratedFirstSuppliers.cs, WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs, WPFTesting/WPFTesting/Shapes/SupplierUIValues.cs, WPFTesting/WPFTesting/SupplierElement.xaml.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
Set the data context as it should be
=> Data now binds

WPFTesting/SpecFlowSupplyChain.MainWindow/Features/CheapestPath.feature.cs, WPFTesting/SpecFlowSupplyChain.MainWindow/Features/MainWindow.feature.cs, WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/WPFTesting/Data/ProductConverter.cs, WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/ComponentToProductTransformer.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/IVendor.cs, WPFTesting/WPFTesting/Models/Supplier.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs, WPFTesting/WPFTesting/WPFTesting.csproj
Changes to the sidebar binding enables binding to the presented lists.
ObservableCollections have replaced lists globally.
=> Sidebar binding changes to Endpoint

WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/Models/ComponentToProductTransformer.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs
Adjustments to resolve some display mishaps.
Reworked ComponentToProductTransformer constructor.
=> Fixed post-merge issues.

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/Models/Supplier.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
=> Advance time stuff

WPFTesting/WPFTesting/Data/ForJsonSuplier.cs, WPFTesting/WPFTesting/Data/InitializedDataProvider.cs
=> Saves suppliers again

WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs
Reworked the logic of the transaction. Now it works, and it only performs logic for each of the production lines if that single production line can be fulfilled.
=> Advance Time Transaction Fix for EndpointElement

WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
#78 
You can now start a shipment line from the Endpoint with out getting an error
=> Can add a shipment starting at Endpoint Element

WPFTesting/WPFTesting/EndpointElement.xaml, WPFTesting/WPFTesting/EndpointElement.xaml.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs
=> Added code that enables the profit label banner.

WPFTesting/WPFTesting/MainWindow.xaml.cs
=> Line Selection works on Endpoint lines

WPFTesting/WPFTesting/Data/EndpointForJson.cs, WPFTesting/WPFTesting/Data/EndpointFromJson.cs, WPFTesting/WPFTesting/Data/InitializedDataProvider.cs
Work on file IO class to make Endpoint nodes respected by the file system.
Issue #103
=> EndpointNode respecting code for issue #103

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/Supplier.cs
=> Data provider and endpoints

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/WPFTesting/Models/IVendor.cs, WPFTesting/WPFTesting/Models/Supplier.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
There is now a test for the progress I made after class
=> Endpoint gets shipment test

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/ProductionTarget.cs, WPFTesting/WPFTesting/Models/StatusEnum.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs
Work towards Story #119
Add-Production-Target button set up.
Binding to list set up 50%.
Binding with simulation duration value works.
=> Production analysis window has list with bindings, and a button to add new product targets.

WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/WPFTesting/Data/ForJsonShipment.cs, WPFTesting/WPFTesting/Data/ForJsonSupplier.cs, WPFTesting/WPFTesting/Data/IInitializedDataProvider.cs, WPFTesting/WPFTesting/Data/InitializedDataProvider.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/Shipment.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs
I don't know why the lines are on top now.... But they load and save alright
=> Lines load from save

WPFTesting/WPFTesting/Data/InitializedDataProvider.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml.cs
I was letting an error be thrown when it didn't have any shipments saved on the files
=> Shipments were breaking when read form bad file

.gitignore, WPFTesting/WPFTesting/FactorSADEfficiencyOptimizer.csproj, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs
=> Add production target action

WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml
Adjustments to Production Analysis window's production target list design
=> Slight changes to UI look & feel.

WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Here is a new class. It is still being birthed
=> Simulator tests

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/WPFTesting/Data/ForJsonShipment.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Methods/SavedShipmentEventArgs.cs, WPFTesting/WPFTesting/Models/Shipment.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/ToolsForViewModel.cs
Added events for:
* adding shipments
* adding products
* deleting shipments
* deleting products
Changed Lists to Observable Collections.
=> Selected shipments window events

WPFTesting/SupplyChainTesting/DataProviderFakeTests.cs, WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
More adjustments to ensure that tests and code aren't broken because of the need for Observable Collections.
=> Lists replaced by Observable Collections.

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml, WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml.cs
Bil of Materials window was created. It now needs data binding to work
=> Bil of Materials window was created. It now needs data binding to work

WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml, WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml.cs
Made some sample data for Bill of Materials to add to the project for demonstration purposes.
=> Made some sample data to add to the project for demostration purposes.

WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Most of the methods I added were selection or simple action methods that I will want to use when assembling the simulation algorithm
=> Steps toward having a day by day simulation

WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml.cs
Switched a stackpanel to a dockpanel. Dockpanel fills the available width.
Added data-path through event binding in Scheduled Shipment component.
Redefined event method to convert names in Scheduled shipment to existing suppliers and endpoints.
=> Quack! Switched an important stackpanel to Dockpanel!

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/UIComponent/Converters/MarginConverter.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs
Visual Touchups for ProductionAnalysisWindow's main bar: now resizes with window.
Slight visual touch-up for MainWindow: Sidebar is hidden until details are needed.
Fix to Margin converter because of changed bindings.
=> UI improvements for a cluster of minor abrasive items.

WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml
UI adjustments and additions. Should look kinda nice now, and the style between windows has been somewhat unified.
Things that have changed:
- Window background between sub-sections.
- List items in Production Analysis Window and Shipments Scheduled window
- Minor margin changes for cleanliness
- Labels for tables
=> Adjusted style of Epic 1 components.

WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Added an element to Analizer Model class to facilitate bindings.
=> Binding DaysToRun fixed

WPFTesting/WPFTesting/Models/AnalyzerTrackers/Issue.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Added production target to the issue class to make it easier to keep track of which target had an issue.
=> Added produciton target to the issue class

WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/SupplyChainTesting/SimulatorTestsHelpers.cs, WPFTesting/WPFTesting/Models/AnalyzerTrackers/Snapshot.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Here is the snapshot for each day that we will need to reset each day when we backtrack.
=> Snapshot Class

WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Snapshot now made for day zero in analyzer model
=> Makes Day zero Snapshots

WPFTesting/WPFTesting/Models/AnalyzerTrackers/Snapshot.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Error on start up stopped.
Models sharing data fixed
=> Bugs and errors helped

WPFTesting/WPFTesting/Models/AnalyzerTrackers/Snapshot.cs
Here is the values that will be in  a snapshot.
=> Profit and spending added to snapshots

WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/IndividualTargetModel.cs
Issue list and graph defined and placed in UI.
ProductionTarget Window now has a means to create this window.
=> Additional functionality

WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
=> Graph is showing the days and money in Endpoint

WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/CopyMaker.cs
-Added ProducitonTargets when make Current Snapshot
=> -Moved Calculation of Components Used

WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/IndividualTargetModel.cs
Binding to viewmodel in IndividualTargetWindow component is now functional.
Graph of product quantity over days theoretically operational.
=> IndividualTargetWindow now binds.

WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml
=> Got rid of the ugly lable

WPFTesting/WPFTesting/FactorySADEfficiencyOptimizer.csproj, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/Product.cs, WPFTesting/WPFTesting/Models/ProductLine.cs, WPFTesting/WPFTesting/Models/ProductionTarget.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs, WPFTesting/WPFTesting/Shapes/SupplierUIValues.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/CopyMaker.cs
-Added a Number Box for Days To Run
-Stopped Error from null Production target
-Moved Copy of Objects from Copy Maker class to Object classes
=> Day num and prod target error

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs
As described in title.
Main Window Issues 4: Save to file does not indicate success.
=> The File popup now closes on save and on lost focus.

WPFTesting/WPFTesting/FactorySADEfficiencyOptimizer.csproj, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs
* Font size increased for readability
* Content scrollable to fit all data presenters
* Background adjusted to resemble colors of Production Target Analysis window.
* Shipment sidebar list adjusted to resemble Production Target list design
Fixed a bug created during MainWindow redesign:
* ScrollViewer does not collapse properly, resolved by collapsing an element containing the ScrollViewer.
=> Adjusted visual look and feel of the side bar in MainWindow

WPFTesting/SupplyChainTesting/SimulationWithMultipleProductsTests.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
Production Targets that require the same resource will order enough for both
=> Step in a good direction

WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE_Version4.cs, WPFTesting/SupplyChainTesting/SimulationWithMultipleProductsTests.cs, WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/ProductionTarget.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs
- Warnings are displayed in the Individual Target Window
-  Doubling Bug When using multiple targets is gone
=> Warnings Visible To User

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/DataProviderFakeTests.cs, WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE_Version4.cs, WPFTesting/SupplyChainTesting/SimulationWithMultipleProductsTests.cs, WPFTesting/SupplyChainTesting/SimulatorTests.cs, WPFTesting/SupplyChainTesting/SimulatorTestsHelpers.cs, WPFTesting/WPFTesting/Components/INodeElement.cs, WPFTesting/WPFTesting/Data/ForJsonEndpoint.cs, WPFTesting/WPFTesting/Data/ForJsonShipment.cs, WPFTesting/WPFTesting/Data/ForJsonSupplier.cs, WPFTesting/WPFTesting/Data/GenneratedFirstSuppliers.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs, WPFTesting/WPFTesting/Shapes/SupplierUIValues.cs, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/EventArguments/RadialNameRoutedEventArgs.cs, WPFTesting/WPFTesting/UIComponent/EventArguments/SaveSupplierEventArgs.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/SupplierElement.xaml, WPFTesting/WPFTesting/UIComponent/SupplierElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/SupplierInventoryWindow.xaml, WPFTesting/WPFTesting/UIComponent/SupplierInventoryWindow.xaml.cs, WPFTesting/WPFTesting/ViewModel/AnalizorModel.cs, WPFTesting/WPFTesting/ViewModel/SupplyChainViewModel.cs, WPFTesting/WPFTesting/ViewModel/ToolsForViewModel.cs
Merge details in first commit of the merge:
~ Redesigned Supplier Element in UI to make it easier to understand
~ Redesigned Supplier sidebar in the main networking window to make it easier to understand / unify visual style.
~ ~ Fixed and hand-tested data binding for Supplier-related elements: Property given INotifyPropertyChanged alongside improved naming conventions.
~ Adjusted the color and font to improve readability.
+ Added Supplier Inventory Window to make the editing of the supplier's components easier, preserving interactability with the other sidebar elements with the font updates.
+ Updated font sizes and weights to improve readability in the Main Window.
=> Supplier inventory window and more

WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE_Version4.cs, WPFTesting/SupplyChainTesting/SimulationWithMultipleProductsTests.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/SupplierInventoryWindow.xaml
= Test fixes
~ Line weight adjustment for clarity & ease of interaction
+ Labels for quantity and price in the SupplierInventory
=> Minor UI and naming work.

WPFTesting/SupplyChainTesting/AdvanceTimeTests.cs, WPFTesting/SupplyChainTesting/DataProviderFakeTests.cs, WPFTesting/SupplyChainTesting/DataProviderTests.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE.cs, WPFTesting/SupplyChainTesting/MockClasses/DataProvider_FAKE_Version4.cs, WPFTesting/SupplyChainTesting/MockClasses/RealEnpointForTest.cs, WPFTesting/WPFTesting/Data/GenneratedFirstSuppliers.cs, WPFTesting/WPFTesting/Data/ProductConverter.cs, WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/Models/Product.cs, WPFTesting/WPFTesting/Models/PublicProd.cs, WPFTesting/WPFTesting/Shapes/EndpointUIValues.cs, WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml, WPFTesting/WPFTesting/UIComponent/BillofMaterials.xaml.cs, WPFTesting/WPFTesting/UIComponent/CommonProductWindow.xaml, WPFTesting/WPFTesting/UIComponent/CommonProductWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShipmentsScheduled.xaml.cs, WPFTesting/WPFTesting/UIComponent/ShippingLineElement.xaml.cs
- Added Common Product window. 
- Found bug. Updates to General Products will render on new windows, but do not generate on already updated windows.
=> Common product window

WPFTesting/WPFTesting/Models/DeliveryLine.cs, WPFTesting/WPFTesting/Models/EndpointNode.cs, WPFTesting/WPFTesting/Models/ProductLine.cs, WPFTesting/WPFTesting/UIComponent/EndpointDetailsWindow.xaml, WPFTesting/WPFTesting/UIComponent/EndpointDetailsWindow.xaml.cs
+ Added Delivery Line lists
+ Redesigned prototype of UI element to have side-by-side design as with Components and Products in inventory
+ Added method to find all routine delivery products to satisfy daily endpoint shipments.
=> Added Delivery Lines to Endpoint Details

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/EndpointDetailsWindow.xaml, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml.cs
~ Endpoint bindings fixed.
~ Endpoint style adjusted.
~ Main Window popout window fixed
=> Endpoint binding and style fixes

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs
Fixed both Target graph and Analyzer graph
=> Graphs look better

WPFTesting/WPFTesting/MainWindow.xaml, WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml
+ Added "make new endpoint" button fallback when all endpoints are removed.
+ Added visual style to sidebar for endpoints and suppliers.
+ Added behavior to register that the file save dialogue was not successful.
=> Added features based on user feedback for QOL

WPFTesting/WPFTesting/UIComponent/EndpointDetailsWindow.xaml
+ Added headers to Component Inventory and Product Inventory in the EndpointDetailsWindow XAML file.
~ Adjusted section titles for readability in Endpoint Details Window.
=> UI changes for inventory section of headers in EndpointDetails window.

WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs
+ Added behavior to hide the "Day Completed" part of the IndividualTargetWindow if the task was not completed.
=> Individual Target Window hides completed day on failure.

WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs
Adjusted erroneous visibility of Completed Day UI field.
Adjusted visibility and readability of Individual Target Window warnings.
=> Warning & Completed field UI fix in Individual Target Window

WPFTesting/WPFTesting/MainWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml, WPFTesting/WPFTesting/UIComponent/EndpointElement.xaml.cs, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml, WPFTesting/WPFTesting/UIComponent/IndividualTargetWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/ProductionAnalysisWindow.xaml.cs, WPFTesting/WPFTesting/UIComponent/SupplierElement.xaml, WPFTesting/WPFTesting/UIComponent/SupplierElement.xaml.cs
+ Added logic that allows a line to connect to suppliers and endpoints without connecting to the radial buttons designed for the purpose.
+ Added logic to ensure that lines both update immediately upon creation and connect to the right spot according to user-assisting business rules.
=> Shipments in Network Graph can now connect to graph elements
